name: Build Rules & Release to Main (jqyisbest/GFWList2AGH)

on:
    workflow_dispatch:
    push:
        branches: [resource]
    schedule:
        - cron: "0 0 * * *"

jobs:
    build_and_release:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout main branch
              uses: actions/checkout@v4

            - name: Step 2 - Build GFWList2AGH rules
              run: |
                  echo "Fetching and running release.sh from source branch..."
                  curl -s "https://raw.githubusercontent.com/jqyisbest/GFWList2AGH/source/release.sh" | sudo bash

            - name: Step 3 - Configure Git
              run: |
                echo "Configuring Git user..."
                git config --global user.name "github-actions[bot]"
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Step 4 - Commit and Push updated rules to main
              run: |
                echo "Checking for generated rule files..."
                if ! ls -d ${{ github.workspace }}/gfwlist2* > /dev/null 2>&1; then
                  echo "No gfwlist2* directories found to commit in ${{ github.workspace }}."
                else
                  echo "Adding gfwlist2* directories to git staging area..."
                  git add ${{ github.workspace }}/gfwlist2*
                fi

                if git diff --quiet && git diff --staged --quiet; then
                  echo "No changes to commit."
                  exit 0
                fi

                COMMIT_DATE=$(TZ="Asia/Shanghai" date +"%Y-%m-%d %H:%M:%S %Z")
                COMMIT_MESSAGE="Update GFWList2AGH rules - $COMMIT_DATE"
                echo "Committing changes with message: $COMMIT_MESSAGE"
                git commit -m "$COMMIT_MESSAGE"
                
                echo "Pushing changes to main branch..."
                git push origin main
